name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md']
    branches: ['main', 'master', 'knots', 'knots-for-community', 'new-config']
  push:
    paths-ignore: ['*.md']
    branches: ['main', 'master', 'knots', 'knots-for-community', 'new-config']

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Checkout services repository
        uses: actions/checkout@v4

      - name: Build the service package
        id: build
        run: |
          sudo apt install -y librsvg2-bin librsvg2-2 imagemagick
          git submodule update --init --recursive
          start-sdk init
          make
          PACKAGE_ID=$(yq -oy ".id" manifest.*)
          echo "package_id=$PACKAGE_ID" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload .s9pk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.package_id }}.s9pk
          path: ./${{ steps.build.outputs.package_id }}.s9pk